export const ACCOUNT_LOGIN_REQUEST = 'ACCOUNT_LOGIN_REQUEST'
export const ACCOUNT_LOGIN_SUCCESS = 'ACCOUNT_LOGIN_SUCCESS'
export const ACCOUNT_LOGIN_FAIL = 'ACCOUNT_LOGIN_FAIL'
export const ACCOUNT_LOGIN_RESET = 'ACCOUNT_LOGIN_RESET'
export const ACCOUNT_LOGOUT = 'ACCOUNT_LOGOUT'

export const ACCOUNT_REGISTER_REQUEST = 'ACCOUNT_REGISTER_REQUEST'
export const ACCOUNT_REGISTER_SUCCESS = 'ACCOUNT_REGISTER_SUCCESS'
export const ACCOUNT_REGISTER_FAIL = 'ACCOUNT_REGISTER_FAIL'
export const ACCOUNT_REGISTER_RESET = 'ACCOUNT_REGISTER_RESET'

export const ACCOUNT_GOOGLE_LOGIN_REQUEST = 'ACCOUNT_GOOGLE_LOGIN_REQUEST'
export const ACCOUNT_GOOGLE_LOGIN_SUCCESS = 'ACCOUNT_GOOGLE_LOGIN_SUCCESS'
export const ACCOUNT_GOOGLE_LOGIN_FAIL = 'ACCOUNT_GOOGLE_LOGIN_FAIL'
export const ACCOUNT_GOOGLE_LOGIN_RESET = 'ACCOUNT_GOOGLE_LOGIN_RESET'

export const ACCOUNT_FACEBOOK_LOGIN_REQUEST = 'ACCOUNT_FACEBOOK_LOGIN_REQUEST'
export const ACCOUNT_FACEBOOK_LOGIN_SUCCESS = 'ACCOUNT_FACEBOOK_LOGIN_SUCCESS'
export const ACCOUNT_FACEBOOK_LOGIN_FAIL = 'ACCOUNT_FACEBOOK_LOGIN_FAIL'
export const ACCOUNT_FACEBOOK_LOGIN_RESET = 'ACCOUNT_FACEBOOK_LOGIN_RESET'

export const ACCOUNT_UPGRADE_ACCOUNT_REQUEST = 'ACCOUNT_UPGRADE_ACCOUNT_REQUEST'
export const ACCOUNT_UPGRADE_ACCOUNT_SUCCESS = 'ACCOUNT_UPGRADE_ACCOUNT_SUCCESS'
export const ACCOUNT_UPGRADE_ACCOUNT_FAIL = 'ACCOUNT_UPGRADE_ACCOUNT_FAIL'
export const ACCOUNT_UPGRADE_ACCOUNT_RESET = 'ACCOUNT_UPGRADE_ACCOUNT_RESET'

export const ACCOUNT_RESET_PASSWORD_REQUEST = 'ACCOUNT_RESET_PASSWORD_REQUEST'
export const ACCOUNT_RESET_PASSWORD_SUCCESS = 'ACCOUNT_RESET_PASSWORD_SUCCESS'
export const ACCOUNT_RESET_PASSWORD_FAIL = 'ACCOUNT_RESET_PASSWORD_FAIL'
export const ACCOUNT_RESET_PASSWORD_RESET = 'ACCOUNT_RESET_PASSWORD_RESET'

export const ACCOUNT_UPDATE_REQUEST = 'ACCOUNT_UPDATE_REQUEST'
export const ACCOUNT_UPDATE_SUCCESS = 'ACCOUNT_UPDATE_SUCCESS'
export const ACCOUNT_UPDATE_FAIL = 'ACCOUNT_UPDATE_FAIL'

