export const CREATE_BARN_REQUEST = 'CREATE_BARN_REQUEST';
export const CREATE_BARN_SUCCESS = 'CREATE_BARN_SUCCESS';
export const CREATE_BARN_FAIL = 'CREATE_BARN_FAIL';
export const CREATE_BARN_RESET = 'CREATE_BARN_RESET';

export const GET_ALL_BARN_REQUEST = 'GET_ALL_BARN_REQUEST';
export const GET_ALL_BARN_SUCCESS = 'GET_ALL_BARN_SUCCESS';
export const GET_ALL_BARN_FAIL = 'GET_ALL_BARN_FAIL';
export const GET_ALL_BARN_RESET = 'GET_ALL_BARN_RESET';

export const GET_BARN_BY_ID_REQUEST = 'GET_BARN_REQUEST';
export const GET_BARN_BY_ID_SUCCESS = 'GET_BARN_SUCCESS';
export const GET_BARN_BY_ID_FAIL = 'GET_BARN_FAIL';
export const GET_BARN_BY_ID_RESET = 'GET_BARN_RESET';

export const UPDATE_BARN_REQUEST = 'UPDATE_BARN_REQUEST';
export const UPDATE_BARN_SUCCESS = 'UPDATE_BARN_SUCCESS';
export const UPDATE_BARN_FAIL = 'UPDATE_BARN_FAIL';
export const UPDATE_BARN_RESET = 'UPDATE'

export const DELETE_BARN_REQUEST = 'DELETE_BARN_REQUEST';
export const DELETE_BARN_SUCCESS = 'DELETE_BARN_SUCCESS';
export const DELETE_BARN_FAIL = 'DELETE_BARN_FAIL';
export const DELETE_BARN_RESET = 'DELETE_BARN_RESET';
