export const CREATE_BREED_REQUEST = 'CREATE_BREED_REQUEST';
export const CREATE_BREED_SUCCESS = 'CREATE_BREED_SUCCESS';
export const CREATE_BREED_FAIL = 'CREATE_BREED_FAIL';
export const CREATE_BREED_RESET = 'CREATE_BREED_RESET';

export const GET_BREED_BY_FARM_ID_REQUEST = 'GET_BREED_BY_FARM_ID_REQUEST';
export const GET_BREED_BY_FARM_ID_SUCCESS = 'GET_BREED_BY_FARM_ID_SUCCESS';
export const GET_BREED_BY_FARM_ID_FAIL = 'GET_BREED_BY_FARM_ID_FAIL';
export const GET_BREED_BY_FARM_ID_RESET = 'GET_BREED_BY_FARM_ID_RESET';

export const GET_BREED_BY_ID_REQUEST = 'GET_BREED_BY_ID_REQUEST';
export const GET_BREED_BY_ID_SUCCESS = 'GET_BREED_BY_ID_SUCCESS';
export const GET_BREED_BY_ID_FAIL = 'GET_BREED_BY_ID_FAIL';
export const GET_BREED_BY_ID_RESET = 'GET_BREED_BY_ID_RESET';

export const UPDATE_BREED_REQUEST = 'UPDATE_BREED_REQUEST';
export const UPDATE_BREED_SUCCESS = 'UPDATE_BREED_SUCCESS';
export const UPDATE_BREED_FAIL = 'UPDATE_BREED_FAIL';
export const UPDATE_BREED_RESET = 'UPDATE_BREED_RESET';

export const DELETE_BREED_REQUEST = 'DELETE_BREED_REQUEST';
export const DELETE_BREED_SUCCESS = 'DELETE_BREED_SUCCESS';
export const DELETE_BREED_FAIL = 'DELETE_BREED_FAIL';
export const DELETE_BREED_RESET = 'DELETE_BREED_RESET';