export const GET_COMMON_FIELD_REQUEST = 'GET_COMMON_FIELD_REQUEST';
export const GET_COMMON_FIELD_SUCCESS = 'GET_COMMON_FIELD_SUCCESS';
export const GET_COMMON_FIELD_FAIL = 'GET_COMMON_FIELD_FAIL';
export const GET_COMMON_FIELD_RESET = 'GET_COMMON_FIELD_RESET';

export const GET_CO_CAU_HEO_REQUEST = 'GET_CO_CAU_HEO_REQUEST';
export const GET_CO_CAU_HEO_SUCCESS = 'GET_CO_CAU_HEO_SUCCESS';
export const GET_CO_CAU_HEO_FAIL = 'GET_CO_CAU_HEO_FAIL';
export const GET_CO_CAU_HEO_RESET = 'GET_CO_CAU_HEO_RESET';

export const GET_TOTAL_IO_BY_MONTH_REQUEST = 'GET_TOTAL_IO_BY_MONTH_REQUEST';
export const GET_TOTAL_IO_BY_MONTH_SUCCESS = 'GET_TOTAL_IO_BY_MONTH_SUCCESS';
export const GET_TOTAL_IO_BY_MONTH_FAIL = 'GET_TOTAL_IO_BY_MONTH_FAIL';
export const GET_TOTAL_IO_BY_MONTH_RESET = 'GET_TOTAL_IO_BY_MONTH_RESET';

export const GET_SALES_OVERVIEW_REQUEST = 'GET_SALES_OVERVIEW_REQUEST';
export const GET_SALES_OVERVIEW_SUCCESS = 'GET_SALES_OVERVIEW_SUCCESS';
export const GET_SALES_OVERVIEW_FAIL = 'GET_SALES_OVERVIEW_FAIL';
export const GET_SALES_OVERVIEW_RESET = 'GET_SALES_OVERVIEW_RESET';

export const GET_INVOICES_REQUEST = 'GET_INVOICES_REQUEST';
export const GET_INVOICES_SUCCESS = 'GET_INVOICES_SUCCESS';
export const GET_INVOICES_FAIL = 'GET_INVOICES_FAIL';
export const GET_INVOICES_RESET = 'GET_INVOICES_RESET';
