export const CREATE_FARM_REQUEST = 'CREATE_FARM_REQUEST';   
export const CREATE_FARM_SUCCESS = 'CREATE_FARM_SUCCESS';
export const CREATE_FARM_FAIL = 'CREATE_FARM_FAIL';
export const CREATE_FARM_RESET = 'CREATE_FARM_RESET';

export const GET_FARM_REQUEST = 'GET_FARM_REQUEST';
export const GET_FARM_SUCCESS = 'GET_FARM_SUCCESS';
export const GET_FARM_FAIL = 'GET_FARM_FAIL';
export const GET_FARM_RESET = 'GET_FARM_RESET';

export const UPDATE_FARM_REQUEST = 'UPDATE_FARM_REQUEST';  
export const UPDATE_FARM_SUCCESS = 'UPDATE_FARM_SUCCESS';
export const UPDATE_FARM_FAIL = 'UPDATE_FARM_FAIL';
export const UPDATE_FARM_RESET = 'UPDATE'

