export const GET_LIST_FOOD_REQUEST = 'GET_LIST_FOOD_REQUEST';
export const GET_LIST_FOOD_SUCCESS = 'GET_LIST_FOOD_SUCCESS';
export const GET_LIST_FOOD_FAIL = 'GET_LIST_FOOD_FAIL';
export const GET_LIST_FOOD_RESET = 'GET_LIST_FOOD_RESET';

export const GET_LIST_FEED_SCHEDULE_REQUEST = 'GET_LIST_FEED_SCHEDULE_REQUEST';
export const GET_LIST_FEED_SCHEDULE_SUCCESS = 'GET_LIST_FEED_SCHEDULE_SUCCESS';
export const GET_LIST_FEED_SCHEDULE_FAIL = 'GET_LIST_FEED_SCHEDULE_FAIL';
export const GET_LIST_FEED_SCHEDULE_RESET = 'GET_LIST_FEED_SCHEDULE_RESET';

export const GET_LIST_FEED_SCHEDULE_BY_USER_REQUEST = 'GET_LIST_FEED_SCHEDULE_BY_USER_REQUEST';
export const GET_LIST_FEED_SCHEDULE_BY_USER_SUCCESS = 'GET_LIST_FEED_SCHEDULE_BY_USER_SUCCESS';
export const GET_LIST_FEED_SCHEDULE_BY_USER_FAIL = 'GET_LIST_FEED_SCHEDULE_BY_USER_FAIL';
export const GET_LIST_FEED_SCHEDULE_BY_USER_RESET = 'GET_LIST_FEED_SCHEDULE_BY_USER_RESET';

export const CREATE_FEED_SCHEDULE_1_DATE_REQUEST = 'CREATE_FEED_SCHEDULE_1_DATE_REQUEST';
export const CREATE_FEED_SCHEDULE_1_DATE_SUCCESS = 'CREATE_FEED_SCHEDULE_1_DATE_SUCCESS';
export const CREATE_FEED_SCHEDULE_1_DATE_FAIL = 'CREATE_FEED_SCHEDULE_1_DATE_FAIL';
export const CREATE_FEED_SCHEDULE_1_DATE_RESET = 'CREATE_FEED_SCHEDULE_1_DATE_RESET';

export const CREATE_FEED_SCHEDULE_MANY_DATE_REQUEST = 'CREATE_FEED_SCHEDULE_MANY_DATE_REQUEST'; 
export const CREATE_FEED_SCHEDULE_MANY_DATE_SUCCESS = 'CREATE_FEED_SCHEDULE_MANY_DATE_SUCCESS';
export const CREATE_FEED_SCHEDULE_MANY_DATE_FAIL = 'CREATE_FEED_SCHEDULE_MANY_DATE_FAIL';
export const CREATE_FEED_SCHEDULE_MANY_DATE_RESET = 'CREATE_FEED_SCHEDULE_MANY_DATE_RESET';

export const CONFIRM_FEED_SCHEDULE_REQUEST = 'CONFIRM_FEED_SCHEDULE_REQUEST';
export const CONFIRM_FEED_SCHEDULE_SUCCESS = 'CONFIRM_FEED_SCHEDULE_SUCCESS';
export const CONFIRM_FEED_SCHEDULE_FAIL = 'CONFIRM_FEED_SCHEDULE_FAIL';
export const CONFIRM_FEED_SCHEDULE_RESET = 'CONFIRM_FEED_SCHEDULE_RESET';

export const DELETE_FEED_SCHEDULE_REQUEST = 'DELETE_FEED_SCHEDULE_REQUEST';
export const DELETE_FEED_SCHEDULE_SUCCESS = 'DELETE_FEED_SCHEDULE_SUCCESS';
export const DELETE_FEED_SCHEDULE_FAIL = 'DELETE_FEED_SCHEDULE_FAIL';
export const DELETE_FEED_SCHEDULE_RESET = 'DELETE_FEED_SCHEDULE_RESET';

