export const GET_LIST_INVOICE_REQUEST = 'GET_LIST_INVOICE_REQUEST';
export const GET_LIST_INVOICE_SUCCESS = 'GET_LIST_INVOICE_SUCCESS';
export const GET_LIST_INVOICE_FAIL = 'GET_LIST_INVOICE_FAIL';
export const GET_LIST_INVOICE_RESET = 'GET_LIST_INVOICE_RESET';

export const CREATE_INVOICE_REQUEST = 'CREATE_INVOICE_REQUEST';
export const CREATE_INVOICE_SUCCESS = 'CREATE_INVOICE_SUCCESS';
export const CREATE_INVOICE_FAIL = 'CREATE_INVOICE_FAIL';
export const CREATE_INVOICE_RESET = 'CREATE_INVOICE_RESET';

export const UPDATE_INVOICE_REQUEST = 'UPDATE_INVOICE_REQUEST';
export const UPDATE_INVOICE_SUCCESS = 'UPDATE_INVOICE_SUCCESS';
export const UPDATE_INVOICE_FAIL = 'UPDATE_INVOICE_FAIL';
export const UPDATE_INVOICE_RESET = 'UPDATE_INVOICE_RESET';

export const CONFIRM_INVOICE_REQUEST = 'CONFIRM_INVOICE_REQUEST';
export const CONFIRM_INVOICE_SUCCESS = 'CONFIRM_INVOICE_SUCCESS';
export const CONFIRM_INVOICE_FAIL = 'CONFIRM_INVOICE_FAIL';
export const CONFIRM_INVOICE_RESET = 'CONFIRM_INVOICE_RESET';

export const DELETE_INVOICE_REQUEST = 'DELETE_INVOICE_REQUEST';
export const DELETE_INVOICE_SUCCESS = 'DELETE_INVOICE_SUCCESS';
export const DELETE_INVOICE_FAIL = 'DELETE_INVOICE_FAIL';
export const DELETE_INVOICE_RESET = 'DELETE_INVOICE_RESET';
