// invoice constants export 

// get list impote
export const INVOICE_LIST_IMPORT_PIG_REQUEST = 'INVOICE_LIST_IMPORT_PIG_REQUEST';
export const INVOICE_LIST_IMPORT_PIG_SUCCESS = 'INVOICE_LIST_IMPORT_PIG_SUCCESS';
export const INVOICE_LIST_IMPORT_PIG_FAIL = 'INVOICE_LIST_IMPORT_PIG_FAIL';
export const INVOICE_LIST_IMPORT_PIG_RESET = 'INVOICE_LIST_IMPORT_PIG_RESET';

export const INVOICE_LIST_EXPORT_PIG_REQUEST = 'INVOICE_LIST_EXPORT_PIG_REQUEST';
export const INVOICE_LIST_EXPORT_PIG_SUCCESS = 'INVOICE_LIST_EXPORT_PIG_SUCCESS';
export const INVOICE_LIST_EXPORT_PIG_FAIL = 'INVOICE_LIST_EXPORT_PIG_FAIL';
export const INVOICE_LIST_EXPORT_PIG_RESET = 'INVOICE_LIST_EXPORT_PIG_RESET';

export const INVOICE_LIST_IMPORT_FOOD_REQUEST = 'INVOICE_LIST_IMPORT_FOOD_REQUEST';
export const INVOICE_LIST_IMPORT_FOOD_SUCCESS = 'INVOICE_LIST_IMPORT_FOOD_SUCCESS';
export const INVOICE_LIST_IMPORT_FOOD_FAIL = 'INVOICE_LIST_IMPORT_FOOD_FAIL';
export const INVOICE_LIST_IMPORT_FOOD_RESET = 'INVOICE_LIST_IMPORT_FOOD_RESET';




