export const GET_LIST_INVOICE_PIG_REQUEST = 'GET_LIST_INVOICE_PIG_REQUEST';
export const GET_LIST_INVOICE_PIG_SUCCESS = 'GET_LIST_INVOICE_PIG_SUCCESS';
export const GET_LIST_INVOICE_PIG_FAIL = 'GET_LIST_INVOICE_PIG_FAIL';
export const GET_LIST_INVOICE_PIG_RESET = 'GET_LIST_INVOICE_PIG_RESET';

export const GET_LIST_INVOICE_IMPORT_PIG_REQUEST = 'GET_LIST_INVOICE_IMPORT_PIG_REQUEST';
export const GET_LIST_INVOICE_IMPORT_PIG_SUCCESS = 'GET_LIST_INVOICE_IMPORT_PIG_SUCCESS';
export const GET_LIST_INVOICE_IMPORT_PIG_FAIL = 'GET_LIST_INVOICE_IMPORT_PIG_FAIL';
export const GET_LIST_INVOICE_IMPORT_PIG_RESET = 'GET_LIST_INVOICE_IMPORT_PIG_RESET';

export const GET_LIST_PIG_IN_INVOICE_IMPORT_PIG_REQUEST = 'GET_LIST_PIG_IN_INVOICE_IMPORT_PIG_REQUEST';
export const GET_LIST_PIG_IN_INVOICE_IMPORT_PIG_SUCCESS = 'GET_LIST_PIG_IN_INVOICE_IMPORT_PIG_SUCCESS';
export const GET_LIST_PIG_IN_INVOICE_IMPORT_PIG_FAIL = 'GET_LIST_PIG_IN_INVOICE_IMPORT_PIG_FAIL';
export const GET_LIST_PIG_IN_INVOICE_IMPORT_PIG_RESET = 'GET_LIST_PIG_IN_INVOICE_IMPORT_PIG_RESET';

export const CREATE_INVOICE_PIG_IMPORT_REQUEST = 'CREATE_INVOICE_PIG_IMPORT_REQUEST';
export const CREATE_INVOICE_PIG_IMPORT_SUCCESS = 'CREATE_INVOICE_PIG_IMPORT_SUCCESS';
export const CREATE_INVOICE_PIG_IMPORT_FAIL = 'CREATE_INVOICE_PIG_IMPORT_FAIL';
export const CREATE_INVOICE_PIG_IMPORT_RESET = 'CREATE_INVOICE_PIG_IMPORT_RESET';

export const CONFIRM_INVOICE_PIG_REQUEST = 'CONFIRM_INVOICE_PIG_REQUEST';
export const CONFIRM_INVOICE_PIG_SUCCESS = 'CONFIRM_INVOICE_PIG_SUCCESS';
export const CONFIRM_INVOICE_PIG_FAIL = 'CONFIRM_INVOICE_PIG_FAIL';
export const CONFIRM_INVOICE_PIG_RESET = 'CONFIRM_INVOICE_PIG_RESET';

export const DELETE_INVOICE_PIG_REQUEST = 'DELETE_INVOICE_PIG_REQUEST';
export const DELETE_INVOICE_PIG_SUCCESS = 'DELETE_INVOICE_PIG_SUCCESS';
export const DELETE_INVOICE_PIG_FAIL = 'DELETE_INVOICE_PIG_FAIL';
export const DELETE_INVOICE_PIG_RESET = 'DELETE_INVOICE_PIG_RESET';

export const CREATE_INVOICE_PIG_EXPORT_REQUEST = 'CREATE_INVOICE_PIG_EXPORT_REQUEST';
export const CREATE_INVOICE_PIG_EXPORT_SUCCESS = 'CREATE_INVOICE_PIG_EXPORT_SUCCESS';
export const CREATE_INVOICE_PIG_EXPORT_FAIL = 'CREATE_INVOICE_PIG_EXPORT_FAIL';
export const CREATE_INVOICE_PIG_EXPORT_RESET = 'CREATE_INVOICE_PIG_EXPORT_RESET';

export const CONFIRM_INVOICE_PIG_EXPORT_REQUEST = 'CONFIRM_INVOICE_PIG_EXPORT_REQUEST';
export const CONFIRM_INVOICE_PIG_EXPORT_SUCCESS = 'CONFIRM_INVOICE_PIG_EXPORT_SUCCESS';
export const CONFIRM_INVOICE_PIG_EXPORT_FAIL = 'CONFIRM_INVOICE_PIG_EXPORT_FAIL';
export const CONFIRM_INVOICE_PIG_EXPORT_RESET = 'CONFIRM_INVOICE_PIG_EXPORT_RESET';
