export const GET_LIST_PARAMETER_REQUEST = 'GET_LIST_PARAMETER_REQUEST'; 
export const GET_LIST_PARAMETER_SUCCESS = 'GET_LIST_PARAMETER_SUCCESS';
export const GET_LIST_PARAMETER_FAIL = 'GET_LIST_PARAMETER_FAIL';
export const GET_LIST_PARAMETER_RESET = 'GET_LIST_PARAMETER_RESET';

export const UPDATE_PARAMETER_REQUEST = 'UPDATE_PARAMETER_REQUEST';
export const UPDATE_PARAMETER_SUCCESS = 'UPDATE_PARAMETER_SUCCESS';
export const UPDATE_PARAMETER_FAIL = 'UPDATE_PARAMETER_FAIL';
export const UPDATE_PARAMETER_RESET = 'UPDATE_PARAMETER_RESET';

