export const CREATE_PIG_REQUEST = 'CREATE_PIG_REQUEST';
export const CREATE_PIG_SUCCESS = 'CREATE_PIG_SUCCESS';
export const CREATE_PIG_FAIL = 'CREATE_PIG_FAIL';
export const CREATE_PIG_RESET = 'CREATE_PIG_RESET';

export const GET_ALL_PIG_REQUEST = 'GET_ALL_PIG_REQUEST';
export const GET_ALL_PIG_SUCCESS = 'GET_ALL_PIG_SUCCESS';
export const GET_ALL_PIG_FAIL = 'GET_ALL_PIG_FAIL';
export const GET_ALL_PIG_RESET = 'GET_ALL_PIG_RESET';

export const GET_PIG_BY_ID_REQUEST = 'GET_PIG_BY_ID_REQUEST';
export const GET_PIG_BY_ID_SUCCESS = 'GET_PIG_BY_ID_SUCCESS';
export const GET_PIG_BY_ID_FAIL = 'GET_PIG_BY_ID_FAIL';
export const GET_PIG_BY_ID_RESET = 'GET_PIG_BY_ID_RESET';

export const GET_PIG_BOAR_REQUEST = 'GET_PIG_BOAR_REQUEST';
export const GET_PIG_BOAR_SUCCESS = 'GET_PIG_BOAR_SUCCESS';
export const GET_PIG_BOAR_FAIL = 'GET_PIG_BOAR_FAIL';
export const GET_PIG_BOAR_RESET = 'GET_PIG_BOAR_RESET';

export const GET_PIG_SOW_REQUEST = 'GET_PIG_SOW_REQUEST';
export const GET_PIG_SOW_SUCCESS = 'GET_PIG_SOW_SUCCESS';
export const GET_PIG_SOW_FAIL = 'GET_PIG_SOW_FAIL';
export const GET_PIG_SOW_RESET = 'GET_PIG_SOW_RESET';

export const UPDATE_PIG_REQUEST = 'UPDATE_PIG_REQUEST';
export const UPDATE_PIG_SUCCESS = 'UPDATE_PIG_SUCCESS';
export const UPDATE_PIG_FAIL = 'UPDATE_PIG_FAIL';
export const UPDATE_PIG_RESET = 'UPDATE_PIG_RESET';

export const DELETE_PIG_REQUEST = 'DELETE_PIG_REQUEST';
export const DELETE_PIG_SUCCESS = 'DELETE_PIG_SUCCESS';
export const DELETE_PIG_FAIL = 'DELETE_PIG_FAIL';
export const DELETE_PIG_RESET = 'DELETE_PIG_RESET';
