export const GET_ALL_PREGNANCY_SCHEDULE_REQUEST = 'GET_ALL_PREGNANCY_SCHEDULE_REQUEST';
export const GET_ALL_PREGNANCY_SCHEDULE_SUCCESS = 'GET_ALL_PREGNANCY_SCHEDULE_SUCCESS';
export const GET_ALL_PREGNANCY_SCHEDULE_FAIL = 'GET_ALL_PREGNANCY_SCHEDULE_FAIL';
export const GET_ALL_PREGNANCY_SCHEDULE_RESET = 'GET_ALL_PREGNANCY_SCHEDULE_RESET';

export const GET_PREGNANCY_SCHEDULE_BY_USER_REQUEST = 'GET_PREGNANCY_SCHEDULE_BY_USER_REQUEST';
export const GET_PREGNANCY_SCHEDULE_BY_USER_SUCCESS = 'GET_PREGNANCY_SCHEDULE_BY_USER_SUCCESS';
export const GET_PREGNANCY_SCHEDULE_BY_USER_FAIL = 'GET_PREGNANCY_SCHEDULE_BY_USER_FAIL';
export const GET_PREGNANCY_SCHEDULE_BY_USER_RESET = 'GET_PREGNANCY_SCHEDULE_BY_USER_RESET';

export const GET_PIG_BY_ID_REQUEST = 'GET_PIG_BY_ID_REQUEST';
export const GET_PIG_BY_ID_SUCCESS = 'GET_PIG_BY_ID_SUCCESS';
export const GET_PIG_BY_ID_FAIL = 'GET_PIG_BY_ID_FAIL';
export const GET_PIG_BY_ID_RESET = 'GET_PIG_BY_ID_RESET';

export const CREATE_PREGNANCY_SCHEDULE_REQUEST = 'CREATE_PREGNANCY_SCHEDULE_REQUEST';
export const CREATE_PREGNANCY_SCHEDULE_SUCCESS = 'CREATE_PREGNANCY_SCHEDULE_SUCCESS';
export const CREATE_PREGNANCY_SCHEDULE_FAIL = 'CREATE_PREGNANCY_SCHEDULE_FAIL';
export const CREATE_PREGNANCY_SCHEDULE_RESET = 'CREATE_PREGNANCY_SCHEDULE_RESET';

export const CONFIRM_PREGNANCY_REQUEST = 'CONFIRM_PREGNANCY_REQUEST';
export const CONFIRM_PREGNANCY_SUCCESS = 'CONFIRM_PREGNANCY_SUCCESS';
export const CONFIRM_PREGNANCY_FAIL = 'CONFIRM_PREGNANCY_FAIL';
export const CONFIRM_PREGNANCY_RESET = 'CONFIRM_PREGNANCY_RESET';

export const CONFIRM_FARROWING_SUCCESS_REQUEST = 'CONFIRM_FARROWING_SUCCESS_REQUEST';
export const CONFIRM_FARROWING_SUCCESS_SUCCESS = 'CONFIRM_FARROWING_SUCCESS_SUCCESS';
export const CONFIRM_FARROWING_SUCCESS_FAIL = 'CONFIRM_FARROWING_SUCCESS_FAIL';
export const CONFIRM_FARROWING_SUCCESS_RESET = 'CONFIRM_FARROWING_SUCCESS_RESET';

export const CONFIRM_FARROWING_FAILURE_REQUEST = 'CONFIRM_FARROWING_FAILURE_REQUEST';
export const CONFIRM_FARROWING_FAILURE_SUCCESS = 'CONFIRM_FARROWING_FAILURE_SUCCESS';
export const CONFIRM_FARROWING_FAILURE_FAIL = 'CONFIRM_FARROWING_FAILURE_FAIL';
export const CONFIRM_FARROWING_FAILURE_RESET = 'CONFIRM_FARROWING_FAILURE_RESET';

export const DELETE_PREGNANCY_SCHEDULE_REQUEST = 'DELETE_PREGNANCY_SCHEDULE_REQUEST';
export const DELETE_PREGNANCY_SCHEDULE_SUCCESS = 'DELETE_PREGNANCY_SCHEDULE_SUCCESS';
export const DELETE_PREGNANCY_SCHEDULE_FAIL = 'DELETE_PREGNANCY_SCHEDULE_FAIL';
export const DELETE_PREGNANCY_SCHEDULE_RESET = 'DELETE_PREGNANCY_SCHEDULE_RESET';
