export const GET_ALL_MEDICINE_REQUEST = 'GET_ALL_MEDICINE_REQUEST';
export const GET_ALL_MEDICINE_SUCCESS = 'GET_ALL_MEDICINE_SUCCESS';
export const GET_ALL_MEDICINE_FAIL = 'GET_ALL_MEDICINE_FAIL';
export const GET_ALL_MEDICINE_RESET = 'GET_ALL_MEDICINE_RESET';

export const GET_ALL_VACCINE_REQUEST = 'GET_ALL_VACCINE_REQUEST';
export const GET_ALL_VACCINE_SUCCESS = 'GET_ALL_VACCINE_SUCCESS';
export const GET_ALL_VACCINE_FAIL = 'GET_ALL_VACCINE_FAIL';
export const GET_ALL_VACCINE_RESET = 'GET_ALL_VACCINE_RESET';

export const GET_ALL_VACCINE_SCHEDULE_REQUEST = 'GET_ALL_VACCINE_SCHEDULE_REQUEST';
export const GET_ALL_VACCINE_SCHEDULE_SUCCESS = 'GET_ALL_VACCINE_SCHEDULE_SUCCESS';
export const GET_ALL_VACCINE_SCHEDULE_FAIL = 'GET_ALL_VACCINE_SCHEDULE_FAIL';
export const GET_ALL_VACCINE_SCHEDULE_RESET = 'GET_ALL_VACCINE_SCHEDULE_RESET';

export const GET_ALL_VACCINE_SCHEDULE_BY_USER_REQUEST = 'GET_ALL_VACCINE_SCHEDULE_BY_USER_REQUEST';
export const GET_ALL_VACCINE_SCHEDULE_BY_USER_SUCCESS = 'GET_ALL_VACCINE_SCHEDULE_BY_USER_SUCCESS';
export const GET_ALL_VACCINE_SCHEDULE_BY_USER_FAIL = 'GET_ALL_VACCINE_SCHEDULE_BY_USER_FAIL';
export const GET_ALL_VACCINE_SCHEDULE_BY_USER_RESET = 'GET_ALL_VACCINE_SCHEDULE_BY_USER_RESET';

export const GET_VACCINE_SCHEDULE_BY_PIG_REQUEST = 'GET_VACCINE_SCHEDULE_BY_PIG_REQUEST';
export const GET_VACCINE_SCHEDULE_BY_PIG_SUCCESS = 'GET_VACCINE_SCHEDULE_BY_PIG_SUCCESS';
export const GET_VACCINE_SCHEDULE_BY_PIG_FAIL = 'GET_VACCINE_SCHEDULE_BY_PIG_FAIL';
export const GET_VACCINE_SCHEDULE_BY_PIG_RESET = 'GET_VACCINE_SCHEDULE_BY_PIG_RESET';

export const GET_PIG_IN_VACCINE_SCHEDULE_REQUEST = 'GET_PIG_IN_VACCINE_SCHEDULE_REQUEST';
export const GET_PIG_IN_VACCINE_SCHEDULE_SUCCESS = 'GET_PIG_IN_VACCINE_SCHEDULE_SUCCESS';
export const GET_PIG_IN_VACCINE_SCHEDULE_FAIL = 'GET_PIG_IN_VACCINE_SCHEDULE_FAIL';
export const GET_PIG_IN_VACCINE_SCHEDULE_RESET = 'GET_PIG_IN_VACCINE_SCHEDULE_RESET';

export const CREATE_VACCINE_SCHEDULE_REQUEST = 'CREATE_VACCINE_SCHEDULE_REQUEST';
export const CREATE_VACCINE_SCHEDULE_SUCCESS = 'CREATE_VACCINE_SCHEDULE_SUCCESS';
export const CREATE_VACCINE_SCHEDULE_FAIL = 'CREATE_VACCINE_SCHEDULE_FAIL';
export const CREATE_VACCINE_SCHEDULE_RESET = 'CREATE_VACCINE_SCHEDULE_RESET';

export const CONFIRM_VACCINE_SCHEDULE_REQUEST = 'CONFIRM_VACCINE_SCHEDULE_REQUEST';
export const CONFIRM_VACCINE_SCHEDULE_SUCCESS = 'CONFIRM_VACCINE_SCHEDULE_SUCCESS';
export const CONFIRM_VACCINE_SCHEDULE_FAIL = 'CONFIRM_VACCINE_SCHEDULE_FAIL';
export const CONFIRM_VACCINE_SCHEDULE_RESET = 'CONFIRM_VACCINE_SCHEDULE_RESET';

